# Generated by Django 5.2.4 on 2025-08-07 12:31

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentor_mentee', '0002_mentorshiprequest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('videoId', models.CharField(max_length=255, unique=True)),
                ('name', models.TextField()),
                ('duration', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('drive', 'Drive'), ('device', 'Device'), ('youtube', 'YouTube')], max_length=10)),
                ('mimetype', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoWatchReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('watchedIntervals', models.JSONField()),
                ('todayIntervals', models.JSONField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('lastWatchedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastWatchTime', models.IntegerField(default=0)),
                ('watchTimePerDay', models.IntegerField(default=0)),
                ('newWatchTimePerDay', models.IntegerField(default=0)),
                ('unfltrdWatchTimePerDay', models.IntegerField(default=0)),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to='mentor_mentee.user')),
                ('video', models.ForeignKey(db_column='videoId', on_delete=django.db.models.deletion.CASCADE, to='report.video', to_field='videoId')),
            ],
            options={
                'unique_together': {('user', 'video', 'date')},
            },
        ),
    ]
