# Generated by Django 5.2.4 on 2025-07-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentor_mentee', '0002_mentorshiprequest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('file', 'File'), ('device', 'Device')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_videos', to='mentor_mentee.mentorship')),
            ],
            options={
                'unique_together': {('mentorship', 'video_id', 'video_type')},
            },
        ),
    ]
