# Generated by Django 5.2.4 on 2025-07-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedvideo',
            name='video_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('file', 'File'), ('device', 'Device'), ('drive', 'Drive')], max_length=10),
        ),
    ]
