# Generated by Django 5.2.4 on 2025-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignedvideo_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedvideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent')], default='pending', max_length=10),
        ),
    ]
