# Generated by Django 5.2.4 on 2026-09-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignedvideo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedvideo',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedvideo',
            name='origin_video_id',
            field=models.CharField(blank=True, default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='assignedvideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='assignedvideo',
            name='video_id',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='assignedvideo',
            name='video_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('drive', 'Drive'), ('iskcon', 'Iskcon'), ('device', 'Device')], max_length=10),
        ),
    ]
