# Generated by Django 5.2.4 on 2026-09-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignedvideo_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedvideo',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignedvideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('seen', 'Seen')], default='pending', max_length=10),
        ),
    ]
