# Generated by Django 5.2.4 on 2025-08-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField()),
                ('receiver_id', models.CharField()),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('receiver_name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('assignment', 'Assignment'), ('report', 'Report')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('viewed', 'Viewed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
