# Generated by Django 5.2.4 on 2025-07-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiprequest',
            name='type',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('mentee', 'Mentee')], default='mentee', max_length=10),
        ),
    ]
