# Generated by Django 5.2.4 on 2026-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_mentee', '0002_mentorshiprequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
